version: '3'
services:
  backend:
    build:
      context: ./src
    networks:
      - gateway
    ports: 
      - 5000:8000
    env_file:
      - ./src/.env
    depends_on:
      - redis
    restart: on-failure  
 
  redis:
    image: redis:5-alpine
    networks: 
      - gateway
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
    restart: on-failure
  
volumes:
  redis_data:
networks:
  gateway: {}
